language: python
sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

# whitelist
branches:
    only:
        - master
        - develop

# install python dependencies
install:
  - pip install codecov
  - pip install pytest-cov
  - pip install pytest-pep8
  - pip install -e .

# run tests
script: 
  - py.test --cov datreant --pep8 datreant

after_success:
  - codecov
