language: python
sudo: false

python:
  - "3.5"
  - "3.6"

# whitelist
branches:
    only:
        - master
        - develop

# install python dependencies
# load my portallocker.git version
install:
  - pip install git+https://github.com/rddaz2013/portalocker.git
  - pip install codecov
  - pip install pytest-cov
  - pip install pytest-pep8
  - pip install -e .

# run tests
script: 
  - py.test --basetemp=mydir --cov src/datreant --pep8 src/datreant

after_success:
  - codecov
