language: python
sudo: required
dist: xenial

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

# whitelist
branches:
    only:
        - master
        - develop

# install python dependencies
install:
  - pip install codecov
  - pip install mock
  - pip install --upgrade pytest
  - pip install pytest-cov
  - pip install pytest-pep8
  - pip install numpy
  - pip install -e .

# run tests
script: 
  - py.test --cov src/datreant --pep8 src/datreant -v --doctest-modules
  # test conversion script runs
  - datreant_07to1 --help

after_success:
  - codecov
