package:
  name: datreant.core
  version: "0.7.0"

source:
  # path: ../../../
  git_url: https://github.com/datreant/datreant.core.git
  # git_branch: master
  git_tag: release-0.7.0

build:
  # noarch_python: True
  script: $PYTHON setup.py install --single-version-externally-managed --record record.txt
  number: 2

requirements:
  build:
    - python
    - pip
    - setuptools
    - asciitree
    - pathlib2
    - scandir
    - six
    - fuzzywuzzy
    - pytest

  run:
    - python
    - asciitree
    - pathlib2
    - scandir
    - six
    - fuzzywuzzy
    - python-levenshtein

test:
  # Python imports should always be done
  imports:
    - datreant
    - datreant.core
    - datreant.core.backends
    - datreant.core.tests

  # please uncomment when building from outside the git repository
  requires:
    - pytest
    - python
    - asciitree
    - pathlib2
    - scandir
    - six
    - fuzzywuzzy
    - python-levenshtein
  files:
    - src/datreant/core/tests
  commands:
    - py.test src


about:
  home: http://datreant.org/
  license: BSD License
  summary: 'persistent, pythonic trees for heterogeneous data'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
