package:
  name: datreant.core
  version: "0.7.0"

source:
  git_url: https://github.com/datreant/datreant.core.git
  git_tag: release-0.7.0

build:
  number: 3

requirements:
  build:
    - python
    - pip
    - setuptools
    - asciitree
    - pathlib2
    - scandir
    - six
    - fuzzywuzzy
    - pytest
    - datreant

  run: &package_deps
    - python
    - asciitree
    - pathlib2
    - scandir
    - six
    - fuzzywuzzy
    - python-levenshtein
    - datreant
    - pytest
    - mock

test:
  imports:
    - datreant.core
    - datreant.core.backends
    - datreant.core.tests
  requires: *package_deps

about:
  home: http://datreant.org/
  license: BSD 3-Clause
  summary: 'persistent, pythonic trees for heterogeneous data'
