package:
  name: asciitree
  version: "0.3.1"

source:
  fn: asciitree-0.3.1.tar.gz
  url: https://pypi.python.org/packages/source/a/asciitree/asciitree-0.3.1.tar.gz
  md5: c0fdd1583971b63b4aa36b7425cbe3c5
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - asciitree = asciitree:main
    #
    # Would create an entry point called asciitree that calls asciitree.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - asciitree

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/mbr/asciitree
  license: MIT
  summary: 'Draws ASCII trees.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
